name: update-repo

on:
  schedule:
    - cron: '0 * * * *'  # hourly
  push:
    branches:
      - master
      
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
        
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED By Nabildzikrika 2024
          echo $d > Dockerfile By Nabildzikrika
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > README.md By Nabildzikrika â¤ï¸â€ğŸ©¹
          
      - name: Commit changes
        run: |
          git config --local user.email "mramdani298@smp.belajar.id"
          git config --local user.name "M. Nabil Dzikrika Ramdani"
          git add -A
          
          arr[0]="ğŸ’œ"
          arr[1]="ğŸ–¤"
          arr[2]="ğŸ’™"
          arr[3]="ğŸ©·"
          arr[4]="ğŸ’£"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.RAJA_OMBAK_WKWKW }}
